# wpa_supplicant configuration — WPA3-SAE client
# Used with vulnerable hostap_2_4 for Dragonblood research

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
pmf=2

network={
    ssid="DragonbloodLab"
    key_mgmt=SAE
    psk="dr4gonfly"
    ieee80211w=2
}
