#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
NUM_RADIOS="${NUM_RADIOS:-3}"

WIFI_LAB_LOG_PREFIX="setup"
source "${PROJECT_DIR}/images/base/lib.sh"

check_prerequisites() {
    require_root

    if [ "$(uname -s)" != "Linux" ]; then
        log_error "This script requires Linux (mac80211_hwsim is a Linux kernel module)"
        log_error "On macOS, use a Linux VM — see docs/MACOS_VM_SETUP.md"
        exit 1
    fi

    local kernel_major
    kernel_major=$(uname -r | cut -d. -f1)
    if [ "${kernel_major}" -lt 4 ]; then
        log_error "Kernel 4.8+ required for mac80211_hwsim. Current: $(uname -r)"
        exit 1
    fi

    if ! modinfo mac80211_hwsim &>/dev/null; then
        log_error "mac80211_hwsim kernel module not available"
        log_error "Install with: apt install linux-modules-extra-\$(uname -r)"
        exit 1
    fi

    if ! command -v docker &>/dev/null; then
        log_error "Docker is not installed"
        exit 1
    fi

    if ! command -v iw &>/dev/null; then
        log_error "iw is not installed (apt install iw)"
        exit 1
    fi

    log_info "All prerequisites met"
}

load_hwsim() {
    if lsmod | grep -q mac80211_hwsim; then
        log_info "mac80211_hwsim already loaded, unloading first"
        modprobe -r mac80211_hwsim
    fi

    log_info "Loading mac80211_hwsim with ${NUM_RADIOS} radios"
    modprobe mac80211_hwsim radios="${NUM_RADIOS}"

    local found_radios
    for attempt in $(seq 1 20); do
        found_radios=$(iw dev | grep -c "Interface wlan" || true)
        if [ "${found_radios}" -ge "${NUM_RADIOS}" ]; then
            break
        fi
        sleep 0.5
    done

    if [ "${found_radios}" -lt "${NUM_RADIOS}" ]; then
        log_error "Expected ${NUM_RADIOS} radios, found ${found_radios}"
        exit 1
    fi

    log_info "Successfully created ${found_radios} virtual radios"
}

write_env_file() {
    local env_file="${PROJECT_DIR}/.env"

    # Detect actual phy names (they increment across hwsim reloads)
    local phys
    phys=($(iw dev | grep -oP 'phy#\K\d+' | sort -n | head -"${NUM_RADIOS}"))

    if [ "${#phys[@]}" -lt "${NUM_RADIOS}" ]; then
        log_error "Expected ${NUM_RADIOS} phys, found ${#phys[@]}"
        exit 1
    fi

    local ifaces
    ifaces=($(iw dev | grep -oP 'Interface \K\S+' | sort | head -"${NUM_RADIOS}"))

    cat > "${env_file}" <<EOF
# Auto-generated by host/setup.sh — do not edit manually
AP_PHY=phy${phys[0]}
AP_IFACE=${ifaces[0]}
CLIENT_PHY=phy${phys[1]}
CLIENT_IFACE=${ifaces[1]}
ATTACKER_PHY=phy${phys[2]}
ATTACKER_IFACE=${ifaces[2]}
NUM_RADIOS=${NUM_RADIOS}
EOF

    log_info "Wrote phy mapping to ${env_file}: AP=phy${phys[0]}/${ifaces[0]} Client=phy${phys[1]}/${ifaces[1]} Attacker=phy${phys[2]}/${ifaces[2]}"
}

main() {
    log_info "=== Wi-Fi Security Lab — Host Setup ==="
    check_prerequisites
    load_hwsim
    write_env_file
    log_info "=== Setup complete. Run 'make build && make up' to start containers ==="
}

main "$@"
